const questionData =[
    {
        "id": 1,
        "level": 1,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "大人の体には、およそいくつの「骨」があるでしょうか？",
        "options": ["約50個", "約100個", "約200個", "約500個"],
        "answer": 2,
        "explanation": "正解は約200個です。生まれたばかりの赤ちゃんはもっと多いのですが、成長するにつれて骨同士がくっついて、大人になると約200個になります。",
        "reference": "Kaibou.pdf [1]"
    },
    {
        "id": 2,
        "level": 1,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "寒いときに体がガタガタと震える「シバリング」。これは何のために起きている？",
        "options": ["筋肉を動かして熱を作るため", "骨を丈夫にするため", "血液の流れを止めるため", "眠気を覚ますため"],
        "answer": 0,
        "explanation": "体温が下がると、体は自動的に筋肉を細かく震わせて熱を作り出そうとします。これを「シバリング」と呼びます。体温の維持には筋肉がとても重要なんです。",
        "reference": "Kaibou.pdf [2]"
    },
    {
        "id": 3,
        "level": 1,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "骨の成分として有名で、骨を硬く丈夫にしている「ミネラル（無機質）」は何？",
        "options": ["鉄分", "カルシウム", "ビタミンC", "ナトリウム"],
        "answer": 1,
        "explanation": "正解はカルシウム。体の中にあるカルシウムの約99%は骨に蓄えられています。骨は体を支えるだけでなく、カルシウムの貯蔵庫でもあるんですよ。",
        "reference": "Kaibou.pdf [2]"
    },
    {
        "id": 4,
        "level": 1,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "血液の成分である「赤血球」や「白血球」は、体のどこで作られている？",
        "options": ["心臓の中", "肝臓の中", "骨の中（骨髄）", "筋肉の中"],
        "answer": 2,
        "explanation": "意外かもしれませんが、血液は骨の内側にある「骨髄（こつずい）」という場所で作られています。骨は血液の工場でもあるんですね。",
        "reference": "Kaibou.pdf [3]"
    },
    {
        "id": 5,
        "level": 1,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "「アキレス腱」などで知られる「腱（けん）」の役割として正しいのはどれ？",
        "options": ["骨と骨をつなぐ", "筋肉と骨をつなぐ", "骨と皮膚をつなぐ", "筋肉同士をつなぐ"],
        "answer": 1,
        "explanation": "「腱」は、筋肉の力を骨に伝えるために、筋肉と骨をつなぐ丈夫なヒモのような組織です。アキレス腱は、ふくらはぎの筋肉をかかとの骨につないでいます。",
        "reference": "Kaibou.pdf [4]"
    },
    {
        "id": 6,
        "level": 1,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "では、骨と骨をつないで、関節が外れないように補強しているバンドのような組織は？",
        "options": ["神経", "血管", "脂肪", "靱帯（じんたい）"],
        "answer": 3,
        "explanation": "骨同士をつないでいるのは「靱帯」です。関節を安定させる役割があります。スポーツなどで無理な力がかかると、ここが傷ついて捻挫（ねんざ）になることがあります。",
        "reference": "Kaibou.pdf [4]"
    },
    {
        "id": 7,
        "level": 1,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "ヒトの首の骨（頸椎）は全部で何個ある？",
        "options": ["3個", "7個", "12個", "30個"],
        "answer": 1,
        "explanation": "ヒトの首の骨は7個です。実はキリンのような首の長い動物も、私たちと同じ7個の骨でできているんですよ。",
        "reference": "Kaibou.pdf [4]"
    },
    {
        "id": 8,
        "level": 1,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "ひじの関節は、ドアの開け閉めのように一方向に動きます。この関節の形を何という？",
        "options": ["球関節（ボールのような関節）", "蝶番関節（チョウツガイのような関節）", "平面関節", "車軸関節"],
        "answer": 1,
        "explanation": "ひじはドアの金具（蝶番：ちょうつがい）のように曲げ伸ばしができるので「蝶番関節」と呼ばれます。肩や股関節のようにグルグル回せる関節とは形が違うんです。",
        "reference": "Kaibou.pdf [5]"
    },
    {
        "id": 9,
        "level": 1,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "背骨を横から見たとき、どのような形をしているのが正常？",
        "options": ["定規のように真っ直ぐ", "S字のようなカーブ", "円のような丸い形", "直角に折れ曲がっている"],
        "answer": 1,
        "explanation": "背骨は緩やかなS字カーブを描いています。このカーブがクッションの役割を果たし、重い頭を支えたり、歩くときの衝撃を和らげたりしています。",
        "reference": "Kaibou.pdf [6]"
    },
    {
        "id": 10,
        "level": 1,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "自分の意志で動かせる筋肉（力こぶを作る筋肉など）を何という？",
        "options": ["随意筋（ずいいきん）", "不随意筋（ふずいいきん）", "心筋", "平滑筋"],
        "answer": 0,
        "explanation": "自分の意志で動かせる筋肉を「随意筋」といい、骨格筋がこれにあたります。逆に、心臓や胃腸の筋肉は意志では動かせないので「不随意筋」と呼ばれます。",
        "reference": "Kaibou.pdf [7], [2]"
    },
    {
        "id": 1,
        "level": 2,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "交通事故による高エネルギー外傷。傷病者は呼吸困難を訴え、吸気時に胸壁の一部が陥没し、呼気時に膨隆する「奇異呼吸」を呈している。この病態の解剖学的説明として適切なものはどれか？",
        "options": ["複数の肋骨が2か所以上で骨折し、胸郭の安定性が失われている（フレイルチェスト）", "胸腔内に空気が貯留し、肺が虚脱している（気胸）", "横隔膜が破裂し、腹腔内臓器が胸腔へ脱出している", "肋間筋の麻痺により、呼吸運動が停止している"],
        "answer": 0,
        "explanation": "複数の肋骨が複数箇所で折れると、その部位が胸郭の動きと逆（奇異）に動くフレイルチェスト（動揺胸郭）となる。これは換気効率を著しく低下させるため、現場では陽圧換気の必要性を考慮しつつ、受傷機転から肺挫傷の合併も疑う必要がある。（Kaibou.pdf p.102）",
        "reference": "Kaibou.pdf p.102"
    },
    {
        "id": 2,
        "level": 2,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "骨盤骨折が疑われる傷病者において、循環血液量減少性ショック（出血性ショック）のリスクが極めて高い解剖学的理由はどれか？",
        "options": ["骨盤内には大腿動脈が走行しているため", "骨盤骨折は必ず大腿骨骨折を合併するため", "後腹膜腔には静脈叢が豊富であり、大量の出血を貯留できるスペースがあるため", "骨盤骨折による痛みで迷走神経反射が起こるため"],
        "answer": 2,
        "explanation": "骨盤腔や後腹膜腔は広大なスペースがあり、静脈叢からの出血で数リットル単位の血液が貯留しうる。現場活動では、骨盤の動揺を確認（動揺痛検査）するのは愛護的観点から「1回のみ」または「省略」し、ショックの兆候があれば早期に骨盤固定を行うことが重要だ。（Kaibou.pdf p.129）",
        "reference": "Kaibou.pdf p.129"
    },
    {
        "id": 3,
        "level": 2,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "大腿骨骨幹部骨折において、周囲の筋組織への内出血により予想される出血量として、救急隊員が想定すべき目安はどれか？",
        "options": ["約100〜200mL", "約300〜500mL", "約1,000〜2,000mL", "約3,000mL以上"],
        "answer": 2,
        "explanation": "大腿部には太い筋肉と血管があり、骨折により周囲組織へ1,000mL〜2,000mL（循環血液量の約20〜40%）もの出血が起こりうる。外出血がなくても太ももの腫脹（腫れ）を確認した時点で、重篤なショックへ移行する準備（輸液の準備や病院選定）が必要だ。（Kaibou.pdf p.72）",
        "reference": "Kaibou.pdf p.72"
    },
    {
        "id": 4,
        "level": 2,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "長時間、倒壊家屋の下敷きになっていた傷病者を救出した。右下肢が長時間圧迫されていた場合、骨格筋の壊死によって血中に放出され、心停止の原因となりうる物質はどれか？",
        "options": ["カルシウムイオン", "カリウムイオン", "ナトリウムイオン", "グルコース"],
        "answer": 1,
        "explanation": "筋細胞が破壊されると、細胞内に多いカリウムが血中に大量放出され、高カリウム血症による不整脈（心停止）を引き起こす（クラッシュ症候群）。圧迫解除直後に容体が急変するリスクがあるため、心電図モニターの早期装着が必須である。（Kaibou.pdf p.59, 62）",
        "reference": "Kaibou.pdf p.59, 62"
    },
    {
        "id": 5,
        "level": 2,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "頸髄損傷が疑われる傷病者。自発呼吸が弱く、腹部のみがペコペコと動く「腹式呼吸」のみが観察された。この呼吸状態から推測される障害部位と機能残存している筋の組み合わせで正しいのはどれか？",
        "options": ["第4頸髄以上の損傷 - 横隔膜（横隔神経）の機能残存", "第7頸髄以下の損傷 - 肋間筋（肋間神経）の機能残存", "第5頸髄以下の損傷 - 横隔膜（横隔神経）の機能残存", "胸髄の損傷 - 腹直筋の機能残存"],
        "answer": 2,
        "explanation": "横隔神経はC3〜C5から出る。C5以下の損傷であれば横隔膜の機能は保たれるが、肋間筋（胸髄支配）が麻痺するため、胸郭が動かず腹部だけが動く呼吸となる。呼吸不全に陥りやすいため、補助換気の準備が必要である。（Kaibou.pdf p.103）",
        "reference": "Kaibou.pdf p.103"
    },
    {
        "id": 6,
        "level": 2,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "下腿部（ふくらはぎ）の骨折疑いで副木固定を行う際、確認すべき末梢動脈拍動の部位として、解剖学的に適切な組み合わせはどれか？",
        "options": ["大腿動脈と膝窩動脈", "後脛骨動脈と足背動脈", "橈骨動脈と尺骨動脈", "総頸動脈と鎖骨下動脈"],
        "answer": 1,
        "explanation": "膝から下の血流評価には、内果（内くるぶし）の後ろを通る「後脛骨動脈」と、足の甲を通る「足背動脈」を確認する。固定前後で脈拍の触知状況に変化がないか必ずチェックすること。（Kaibou.pdf p.109）",
        "reference": "Kaibou.pdf p.109"
    },
    {
        "id": 7,
        "level": 2,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "高齢者が転倒し、「足の付け根が痛くて立てない」と訴えている。患肢が「短縮」し「外旋（外側を向いている）」している場合、最も疑われる骨折部位はどこか？",
        "options": ["骨盤骨折", "大腿骨頸部骨折", "膝蓋骨骨折", "脛骨骨折"],
        "answer": 1,
        "explanation": "大腿骨頸部（または転子部）骨折の典型的な肢位である。腸腰筋などの筋肉に引っ張られて足が短くなり、重力と筋の作用で外側へ開く。無理に足をまっすぐにしようとせず、その肢位のまま愛護的に搬送する必要がある。（Kaibou.pdf p.73）",
        "reference": "Kaibou.pdf p.73"
    },
    {
        "id": 8,
        "level": 2,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "外傷による神経麻痺の評価において、デルマトーム（皮膚分節）の知識は重要である。「乳頭の高さ」の感覚が消失している場合、障害が疑われる脊髄レベルはどれか？",
        "options": ["C4", "Th4 (T4)", "Th10 (T10)", "L1"],
        "answer": 1,
        "explanation": "乳頭レベルはTh4、剣状突起はTh8、臍（へそ）はTh10、鼠径部はL1である。麻痺のレベル（高位）が時間経過とともに上がってくる場合は緊急性が高い。現場での麻痺レベル確認の指標として暗記しておくべき知識だ。（Kaibou.pdf p.86）",
        "reference": "Kaibou.pdf p.86"
    },
    {
        "id": 9,
        "level": 2,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "ショック体位（下肢挙上）をとらせる生理学的な根拠として、骨格筋系・静脈系の機能に関連するものはどれか？",
        "options": ["下肢の動脈圧を下げるため", "静脈弁の働きと重力を利用し、貯留した血液を心臓へ還流させるため", "骨格筋をリラックスさせて酸素消費量を減らすため", "腹圧を上げて大動脈の血流を良くするため"],
        "answer": 1,
        "explanation": "静脈は「容量血管」と呼ばれ血液の多くを貯留している。下肢を挙上することで、重力を利用して静脈還流量（前負荷）を増やし、心拍出量を維持するのが目的である。ただし、頭部外傷や心不全がある場合は禁忌となるので注意せよ。（Kaibou.pdf p.116）",
        "reference": "Kaibou.pdf p.116"
    },
    {
        "id": 10,
        "level": 2,
        "category": "anatomy",
        "subCategory": "musculoskeletal",
        "text": "関節の固定処置において、靱帯損傷（捻挫）か骨折か判別が難しい場合でも、原則として行うべき処置はどれか？",
        "options": ["疼痛が強いため、冷罨法のみ行い固定はしない", "関節を他動的に動かして、可動域を確認してから固定する", "骨折があるものとして、上下の関節を含めて固定する", "脱臼を整復してから固定する"],
        "answer": 2,
        "explanation": "現場で骨折か捻挫かを完全に区別することは困難である。したがって、「疑わしきは骨折として扱う」のが鉄則。患部の動揺を防ぐため、損傷部位の上下の関節を含めて固定し、二次損傷を防ぐ。（Kaibou.pdf p.153）",
        "reference": "Kaibou.pdf p.153"
    },
    {
        "id": 1,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "人間の体にある「神経」は、大きく2つのグループに分けられます。脳と脊髄からなる、体の司令塔チームを何という？",
        "options": ["末梢神経系", "中枢神経系", "自律神経系", "運動神経系"],
        "answer": 1,
        "explanation": "脳と脊髄は、体中の情報をまとめて判断を下す「中枢（ちゅうすう）」の役割をしています。これに対して、手足などに伸びているのが末梢神経です。（Kaibou.pdf [1]）",
        "reference": "Kaibou.pdf [1]"
    },
    {
        "id": 2,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "脳の中でも一番大きく、ものを考えたり、記憶したり、言葉を話したりする働きをしている部分はどこ？",
        "options": ["小脳（しょうのう）", "脳幹（のうかん）", "大脳（だいのう）", "脊髄（せきずい）"],
        "answer": 2,
        "explanation": "大脳は脳の大部分を占めていて、思考、記憶、感情、運動の命令など、人間らしい高度な働きを担っています。（Kaibou.pdf [2]）",
        "reference": "Kaibou.pdf [2]"
    },
    {
        "id": 3,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "自転車に乗ったり、平均台を渡ったりするときに重要な、体の「バランス」をとる役割をしている脳はどこ？",
        "options": ["大脳", "小脳", "間脳", "中脳"],
        "answer": 1,
        "explanation": "小脳は、運動の調節やバランス感覚（平衡感覚）を担当しています。ここがうまく働かないと、スムーズに動けたり歩けたりできなくなります。（Kaibou.pdf [3]）",
        "reference": "Kaibou.pdf [3]"
    },
    {
        "id": 4,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "呼吸をしたり心臓を動かしたりと、生きるために絶対に必要な働きをコントロールしている、脳の奥の部分（幹）は何？",
        "options": ["脳幹（のうかん）", "大脳辺縁系", "前頭葉", "頭頂葉"],
        "answer": 0,
        "explanation": "脳幹（中脳・橋・延髄）には、呼吸や循環（心臓）の中枢があります。ここが傷つくと命にかかわるため、「生命維持の中枢」とも呼ばれます。（Kaibou.pdf [4]）",
        "reference": "Kaibou.pdf [4]"
    },
    {
        "id": 5,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "自分の意志とは関係なく、心臓や胃腸などを自動的にコントロールしている神経をまとめて何という？",
        "options": ["運動神経", "感覚神経", "自律神経", "脳神経"],
        "answer": 2,
        "explanation": "自律神経は、寝ている間も自動的に内臓を動かして体の環境を整えています。交感神経と副交感神経の2つがあります。（Kaibou.pdf [5]）",
        "reference": "Kaibou.pdf [5]"
    },
    {
        "id": 6,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "運動したり、緊張したり、興奮しているときに活発に働き、「闘うモード」にする自律神経はどっち？",
        "options": ["交感神経", "副交感神経", "三叉神経", "迷走神経"],
        "answer": 0,
        "explanation": "交感神経は「闘争か逃走か」の神経とも呼ばれ、心拍数を上げたり瞳孔を開いたりして、体を活動的な状態にします。（Kaibou.pdf [5]）",
        "reference": "Kaibou.pdf [5]"
    },
    {
        "id": 7,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "逆に、ご飯を食べてリラックスしているときや、眠っているときに活発になる「お休みモード」の自律神経は？",
        "options": ["交感神経", "副交感神経", "坐骨神経", "視神経"],
        "answer": 1,
        "explanation": "副交感神経は、体をリラックスさせ、消化を助けたり、休息を取らせたりしてエネルギーを蓄える働きをします。（Kaibou.pdf [5]）",
        "reference": "Kaibou.pdf [5]"
    },
    {
        "id": 8,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "熱い鍋に触った瞬間、考えずに手を引っ込めるような反応を「反射」といいます。このとき、信号はどこで折り返している？",
        "options": ["大脳まで行って戻る", "脊髄（せきずい）で折り返す", "心臓で折り返す", "筋肉で折り返す"],
        "answer": 1,
        "explanation": "危険から身を守るための反射（脊髄反射）は、大脳まで行って考える時間を節約するため、背骨の中にある脊髄で信号がＵターンして筋肉に命令を出します。（Kaibou.pdf [6]）",
        "reference": "Kaibou.pdf [6]"
    },
    {
        "id": 9,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "右側の大脳は、体のどちら側をコントロールしていることが多い？",
        "options": ["右半身", "左半身", "上半身", "下半身"],
        "answer": 1,
        "explanation": "神経の経路は首のあたり（延髄など）で左右が交差するため、右の脳は左半身を、左の脳は右半身をコントロールしています。（Kaibou.pdf [3], [7]）",
        "reference": "Kaibou.pdf [3], [7]"
    },
    {
        "id": 10,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "脳はとても柔らかい組織です。頭蓋骨の中で脳を守るために、脳が浸かっている液体の名前は？",
        "options": ["血液", "リンパ液", "脳脊髄液（ずいえき）", "消化液"],
        "answer": 2,
        "explanation": "脳と脊髄は「脳脊髄液（のうせきずいえき）」という無色透明な液体の中に浮かんでいて、衝撃から守られています。（Kaibou.pdf [8]）",
        "reference": "Kaibou.pdf [8]"
    },
    {
        "id": 11,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "脳から直接出ている神経（脳神経）は、全部で何ペアある？",
        "options": ["3ペア", "7ペア", "12ペア", "31ペア"],
        "answer": 2,
        "explanation": "脳神経は左右12対（ペア）あります。それぞれ視覚、嗅覚、顔の動きなどを担当しています。（Kaibou.pdf [9]）",
        "reference": "Kaibou.pdf [9]"
    },
    {
        "id": 12,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "背骨の中を通っている神経の束「脊髄」からは、体中に向かって何ペアの神経が出ている？",
        "options": ["12ペア", "20ペア", "31ペア", "50ペア"],
        "answer": 2,
        "explanation": "脊髄神経は、首、胸、腰、お尻の骨の間から左右に出ており、合計で31対（ペア）あります。（Kaibou.pdf [10]）",
        "reference": "Kaibou.pdf [10]"
    },
    {
        "id": 13,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "ものを見るために、目から脳へ情報を送っている神経の名前は？",
        "options": ["嗅神経（きゅうしんけい）", "視神経（ししんけい）", "聴神経（ちょうしんけい）", "顔面神経"],
        "answer": 1,
        "explanation": "網膜に映った光の信号を脳に伝えるのが「視神経」です。（Kaibou.pdf [9]）",
        "reference": "Kaibou.pdf [9]"
    },
    {
        "id": 14,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "顔の表情を作ったり、笑顔を作ったりするために筋肉を動かしている神経は？",
        "options": ["三叉神経", "視神経", "顔面神経", "迷走神経"],
        "answer": 2,
        "explanation": "「顔面神経」は表情筋を動かす神経です。これが麻痺すると、顔が動かしにくくなったり、目が閉じられなくなったりします。（Kaibou.pdf [11]）",
        "reference": "Kaibou.pdf [11]"
    },
    {
        "id": 15,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "脳神経の中で一番分布範囲が広く、お腹の内臓（胃や腸）まで伸びて働きを調整している神経は？",
        "options": ["迷走神経（めいそうしんけい）", "舌下神経", "副神経", "動眼神経"],
        "answer": 0,
        "explanation": "「迷走神経」は脳から出て首を通り、胸や腹部の内臓にまで達する長い神経で、副交感神経として内臓の働きを調整します。（Kaibou.pdf [12]）",
        "reference": "Kaibou.pdf [12]"
    },
    {
        "id": 16,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "暗い場所に行ったり、驚いたりしたとき、目の「瞳孔（ひとみ）」はどうなる？",
        "options": ["小さくなる（縮瞳）", "大きくなる（散瞳）", "四角くなる", "変化しない"],
        "answer": 1,
        "explanation": "暗い場所で光を多く取り入れたり、興奮して交感神経が働くと、瞳孔は大きく開きます（散瞳）。（Kaibou.pdf [13], [14]）",
        "reference": "Kaibou.pdf [13], [14]"
    },
    {
        "id": 17,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "脳の細胞（ニューロン）同士がつながって情報をやり取りしている「つなぎ目」の部分を何という？",
        "options": ["シナプス", "カプセル", "バッテリー", "アンテナ"],
        "answer": 0,
        "explanation": "神経細胞同士の接合部は「シナプス」と呼ばれます。ここで化学物質を出して、次の細胞へ信号を伝えます。（Kaibou.pdf [15]）",
        "reference": "Kaibou.pdf [15]"
    },
    {
        "id": 18,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "脳梗塞などで、言葉がうまく話せなくなったり理解できなくなったりする症状を何という？",
        "options": ["失語症（しつごしょう）", "健忘症", "不眠症", "認知症"],
        "answer": 0,
        "explanation": "大脳にある言語中枢（ブローカ野やウェルニッケ野）が傷つくと、言葉が出てこなくなったり、言葉の意味が分からなくなったりする「失語症」になります。（Kaibou.pdf [16]）",
        "reference": "Kaibou.pdf [16]"
    },
    {
        "id": 19,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "内臓の働きを調節する自律神経の司令塔で、体温調節や食欲などもコントロールしている脳の場所は？",
        "options": ["視床下部（ししょうかぶ）", "小脳", "脊髄", "海馬"],
        "answer": 0,
        "explanation": "間脳にある「視床下部」は、自律神経やホルモンの総元締めで、体温、食欲、睡眠などを調節し、体の環境を一定に保っています。（Kaibou.pdf [3]）",
        "reference": "Kaibou.pdf [3]"
    },
    {
        "id": 20,
        "level": 1,
        "category": "anatomy",
        "subCategory": "nervous",
        "text": "お医者さんが患者さんの足の裏を棒でこすったり、膝を叩いたりするのは何を見ている？",
        "options": ["くすぐったいか確認している", "骨の硬さを調べている", "神経の反射が正常か見ている", "筋肉の量を測っている"],
        "answer": 2,
        "explanation": "膝を叩くと足が勝手に跳ね上がる「膝蓋腱反射」などの反射を見ることで、神経の経路が正常につながっているかを確認しています。（Kaibou.pdf [6]）",
        "reference": "Kaibou.pdf [6]"
    }
]